enum msgType_t
{
proCV_startSamplingReq,
proCV_startSamplingRsp,

proCV_stopSamplingReq,
proCV_stopSamplingRsp,

proCV_setSampleModeContinuousReq,
proCV_setSampleModeContinuousRsp,

proCV_setSampleModeTimedReq,
proCV_setSampleModeTimedRsp,

proCV_setSampleModeCommandReq,
proCV_setSampleModeCommandRsp,

proCV_startViewLoggedDataReq,
proCV_startViewLoggedDataRsp,

proCV_stopViewLoggedDataReq,
proCV_stopViewLoggedDataRsp,

proCV_setLoggedDataLineCallbackReq,
proCV_setLoggedDataLineCallbackRsp,

proCV_setLoggedDataSubstrCallbackReq,
proCV_setLoggedDataSubstrCallbackRsp,

proCV_eraseLoggedDataReq,
proCV_eraseLoggedDataRsp,

proCV_getStatusReq,
proCV_getStatusRsp,

proCV_setClockTimeReq,
proCV_setClockTimeRsp,

proCV_setBaudRateReq,
proCV_setBaudRateRsp,

proCV_restoreFactoryDefaultReq,
proCV_restoreFactoryDefaultRsp,

proCV_scheduleZeroReq,
proCV_scheduleZeroRsp,

proCV_startSingleSampleReq,
proCV_startSingleSampleRsp
}